# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-11 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=-1)),
                ('use_agree', models.BooleanField(default=0)),
                ('back_result', models.IntegerField(default=-1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChronicKidneyDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u80be\u708e', max_length=50)),
                ('age', models.IntegerField()),
                ('bp', models.BooleanField()),
                ('sg', models.BooleanField()),
                ('al', models.IntegerField()),
                ('su', models.IntegerField()),
                ('rbc', models.BooleanField()),
                ('pc', models.BooleanField()),
                ('pcc', models.BooleanField()),
                ('ba', models.BooleanField()),
                ('bgr', models.FloatField()),
                ('bu', models.FloatField()),
                ('sc', models.FloatField()),
                ('sod', models.FloatField()),
                ('pot', models.FloatField()),
                ('hemo', models.FloatField()),
                ('pcv', models.IntegerField()),
                ('wc', models.IntegerField()),
                ('rc', models.BooleanField()),
                ('htn', models.BooleanField()),
                ('dm', models.BooleanField()),
                ('cad', models.BooleanField()),
                ('appet', models.BooleanField()),
                ('pe', models.BooleanField()),
                ('ane', models.BooleanField()),
                ('check_inf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AiServer.CheckInf')),
            ],
        ),
        migrations.CreateModel(
            name='HeartDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u5fc3\u810f\u75c5', max_length=50)),
                ('age', models.IntegerField()),
                ('sex', models.BooleanField()),
                ('cp', models.IntegerField()),
                ('tresbps', models.FloatField()),
                ('chol', models.FloatField()),
                ('fbs', models.FloatField()),
                ('restecg', models.IntegerField()),
                ('thalach', models.IntegerField()),
                ('exang', models.BooleanField()),
                ('oldpeak', models.FloatField()),
                ('slope', models.IntegerField()),
                ('ca', models.IntegerField()),
                ('thal', models.IntegerField()),
                ('check_inf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AiServer.CheckInf')),
            ],
        ),
    ]
