# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-15 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinf',
            name='disease_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
