# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-15 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiServer', '0002_checkinf_disease_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinf',
            name='disease_id',
            field=models.IntegerField(null=True),
        ),
    ]
