# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-15 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiServer', '0003_auto_20170715_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronickidneydisease',
            name='sg',
            field=models.FloatField(),
        ),
    ]
