# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-15 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AiServer', '0004_auto_20170715_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinf',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
